name: Build, Scan, and Deploy Container App to Azure Web App - ccsecw2webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Initialize_Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://ccsecw2reg.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_0b5bac57b0bd4ca2b524d5c48f14a083 }}

      - name: Build container image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          push: false  
          tags: ccsecw2reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}/myapp:${{ github.sha }}
          file: ./Dockerfile

  Snyk:
    needs: Initialize_Build
    runs-on: ubuntu-latest
    steps:
      - name: Check SNYK_TOKEN
        run: echo "SNYK_TOKEN is ${{ secrets.SNYK_TOKEN }}"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        run: |
          docker pull snyk/snyk-cli:docker
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            snyk/snyk-cli:docker test ccsecw2reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}/myapp:${{ github.sha }} \
            --file=./Dockerfile \
            --severity-threshold=high \
            --json | tee snyk_report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
      - name: Upload Snyk scan results
        uses: actions/upload-artifact@v3
        with:
          name: snyk-scan-results
          path: snyk_report.json 

  Finalize_Build:
    needs: Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ccsecw2reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}/myapp:${{ github.sha }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Finalize_Build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ccsecw2webapp'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_628f743c4b3a44dfa39c8a57b309b0a3 }}
          images: 'ccsecw2reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}/myapp:${{ github.sha }}'