name: Build, Push, Scan, and Deploy Container App to Azure Web App - ccsecw2webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_push_scan_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
#
    - name: Build and push container image to Docker Hub
      id: build-and-push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: yourusername/myapp:${{ github.sha }}
        file: ./Dockerfile

    - name: Run Snyk to check Docker image for vulnerabilities
      run: |
        docker pull yourusername/myapp:${{ github.sha }}
        docker run -v $PWD:/app -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk-cli:latest test --docker yourusername/myapp:${{ github.sha }}

    - name: Upload Snyk Report
      uses: actions/upload-artifact@v2
      with:
        name: snyk-report
        path: snyk-report.json

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_scan_and_deploy
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ccsecw2webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_628f743c4b3a44dfa39c8a57b309b0a3 }}
        images: 'yourusername/myapp:${{ github.sha }}'
